### ISSUE TITLE
ver 0.20

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#32]
# ver 0.20
**회원 가입 기능 관련**
1.  DB 구조 -> VO 클래스 작성
2.  프론트 작업
3. Controller - Service -DAO
4. myBatis 매핑

## Description
회원가입에 대한 기능 구현을 위해 코드 작업 실시
+ 병합 테스트
1. 필드값 설정을 위해 VO 클래스 작성. DB설계 보고서 참조
2. 기본적인 UI 확인 및 구조 작성 + 컨트롤러 매핑을 위해 기존 요청 URL 재검토
3. Controller - Service -DAO 기본적인 구조 생성 및 회원 가입을 위한 메소드 작업
4. myBatis 매핑을 위해 기본적인 SQL 문 작성 , mybatis-config.xml 설정

## TODO
- [x] **VO 클래스 작성**
- [x] **UI 확인 및 구조 작성**
- [x] **기존 URL 재설정**
- [x] **Controller - Service -DAO 기본적인 구조 생성**
- [x] **회원 가입을 위한 메소드 작업**
- [x] **SQL문 작성**
- [x] **mybatis-config.xml 설정**

## ETC
**기타사항 이곳을 지우고 입력하세요**

**Comment by goodplan77** [comment]
1. 회원가입 페이지

**Comment by goodplan77** [comment]
1. UI 확인 재 필요

**Comment by goodplan77** [comment]
### 현재 업무 프로세스가 확립되지 않은 관계로 , 기본설정을 다시 한뒤 재시작 하는것이 바람직하다 생각합니다.
