### ISSUE TITLE
ver 0.21

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#36]
# ver 0.21
**1. 회원가입 추가 작업 완료**
**2. 로그인 기능 작업**

## Description
- 회원 가입 필드 별 최대 입력 길이 설정
- 일부 필드 password 형태 재 설정
- 로그인 UI 작업
- 로그인 컨트롤러 , Service , DAO 구조 설정 및 로직 설정
- 로그인 관련 mybatis 매핑 작업

## TODO
- [x] **회원 가입 필드 별 최대 입력 길이 설정**
- [x] **일부 필드 password 형태 재 설정**
- [x] **로그인 UI 작업**
- [x] **로그인 컨트롤러 , Service , DAO 구조 설정 및 로직 설정**
- [x] **로그인 관련 mybatis 매핑 작업**

## ETC
추가 작업 : 로깅 작업 추가 (SQL 콘솔 출력)

**Comment by goodplan77** [comment]
**추가 작업 : 이메일체크확인기능**
- [x] **회원가입 : 이메일체크**
