### ISSUE TITLE
ver 0.30

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#37]
# ver 0.30
**1. 주문 작업**

## Description
- 주문 관련 VO 클래스 생성
- 컨트롤러 , Service , DAO 클래스 생성 및 비즈니스 로직 생성
- mybatis 매핑 설정
- UI 연결

## TODO
- [x] ** 주문 관련 VO 클래스 생성**
- [ ] **컨트롤러 , Service , DAO 클래스 생성 및 비즈니스 로직 생성**
- [ ] **mybatis 매핑 설정**
- [ ] **UI 연결**

**Comment by goodplan77** [comment]
VO 클래스 생성만 완료 . 이후 재정비
