### ISSUE TITLE
ver 0.40

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#43]
# ver 0.40
**1.일부 프론트 디자인 수정**
**2. USER 관련 로직 구현 및 수정**
**3. ORDER 관련 로직 구현 및 수정**
**4. 문의(Inquiry) 관련 로직 구현 및 수정**

## Description
1. 아이디 찾기 UI
2. 문의 UI
3. footer CSS 수정
4. 이메일 중복 검사 로직 구현
5. 주문 등록 로직 , DB 연결 구현
6. 1대1 문의 로직 , DB 연결 구현

## TODO
- [x] **1. 아이디 찾기 UI**
- [x] **2. 문의 UI**
- [x] **3. footer CSS 수정**
- [x] **4. 이메일 중복 검사 로직 구현**
- [x] **5. 주문 등록 로직 , DB 연결 구현**
- [x] **6. 1대1 문의 로직 , DB 연결 구현**

## ETC
채팅 룸 관련 로직 구현 시작
