### ISSUE TITLE
ver 0.40 (bugfix)

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#45]
# bugFix
1. 개인 확인용 DB 연결 설정 문제
2. 회원 가입 UI 오류
3. 주문 입력시 ajax 동기화 처리 부분 오류

## Description
1. DB 연결 재 설정
2. 회원 가입 UI 수정
3. 주문 입력 오류 수정

## TODO
- [x] **1. DB 연결 재 설정**
- [x] **2. 회원 가입 UI 수정**
- [x] **3. 주문 입력 오류 수정**

## ETC
**기타사항 이곳을 지우고 입력하세요**
