### ISSUE TITLE
ver 0.60

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#49]
# ver 0.60
1. 회원 탈퇴
2. 문의 리뷰
3. 로그인 체크 기능
4. 스케줄러 - 필요없는 파일 삭제 기능
5. 기타 UI 작업

## Description
1. 회원 탈퇴
2. 문의 리뷰
3. 로그인 체크 기능
4. 스케줄러 - 필요없는 파일 삭제 기능
5. 기타 UI 작업

## TODO
- [x] **1. 회원 탈퇴**
- [x] **2. 문의 리뷰**
- [x] **3. 로그인 체크 기능**
- [x] **4. 스케줄러 - 필요없는 파일 삭제 기능**
- [x] **5. 기타 UI 작업**

...

## ETC
- [x] 웹소켓을 이용한 채팅 기능

**Comment by goodplan77** [comment]
## 추가 작업 목록
1. 메인 홈페이지에 긴급 주문 목록 추가
2. 문의 상세보기 UI 변경
3. 헤더 UI 변경
4. 일부 필요없는 소스코드 삭제
5. DB 테이블 변경 및 mapper 수정

**Comment by goodplan77** [comment]
웹소켓의 경우 다음 버전에서 통합 예정
