### ISSUE TITLE
ver 0.70

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#52]
# ver 0.70
1. 주문 및 라이더 연결

## Description
1. 주문 테이블 수정
2. 라이더 - 주문 수락시 주문의 상태 변경 로직 생성
3. 2 관련 프론트 UI 작업 실시

## TODO
- [x] **1. 주문 테이블 수정**
- [x] **2. 라이더 - 주문 수락시 주문의 상태 변경 로직 생성**
- [x] **3. 2 관련 프론트 UI 작업 실시**

## ETC
- [x] **웹 소켓을 이용한 채팅 기능**
