### ISSUE TITLE
ver 0.80

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#54]
# ver 0.80
1. 주문 - 라이더 연결 기능
2. 주문 - 채팅방 연결 완료 및 확인 작업
3. 각종 UI 수정 작업

## Description
1. 현재 로그인 한 유저가 라이더 인 경우 , 라이더의 정보를 가져오기
2. 라이더 정보를 통해 수락 , 종료 버튼 활성화
3. 채팅방 추가 작업 실시 (추가 코멘트)
4. 각종 UI 작업

## TODO
- [x] **1. 현재 로그인 한 유저가 라이더 인 경우 , 라이더의 정보를 가져오기**
- [x] **2. 라이더 정보를 통해 수락 , 종료 버튼 활성화**

### TODO - UI
- [ ] 메인 페이지 - 최근 게시글
- [ ] 로그인
- [ ] 아이디 찾기
- [ ] 비밀번호 찾기
- [ ] 배달 요청 목록
- [ ] 주문 상세 보기
- [ ] 문의 목록
- [ ] 마이 페이지 - 고객
- [ ] 마이 페이지 - 라이더
- [ ] 내가 쓴글

## ETC
수정중

**Comment by goodplan77** [comment]
UI 수정 사항은 다음 ver 0.90 으로 이전
