### ISSUE TITLE
ver 0.90

### ISSUE THREAD

**Issue by goodplan77** [goodplan77/Semiproject#56]
# ver 0.90
1. 라이더 평점 추가 및 설정
2. ver 0.80 UI 수정 작업 완료

## Description
1. 라이더 평점 추가 및 설정
2. 주문 완료시 라이더의 평점 업데이트
3. ver 0.80 UI 수정 작업 완료

## TODO
- [x] **1. 라이더 평점 추가**
- [x] **2. 주문 완료시 라이더의 평점 업데이트**
- [x] **3. ver 0.80 UI 수정 작업 완료**

### TODO - UI
- [x] 메인 페이지 - 최근 게시글
- [x] 로그인
- [x] 아이디 찾기
- [x] 비밀번호 찾기
- [x] 배달 요청 목록
- [x] 주문 상세 보기
- [x] 문의 목록
- [x] 마이 페이지 - 고객
- [x] 마이 페이지 - 라이더
- [x] 내가 쓴글

## ETC
**기타사항 이곳을 지우고 입력하세요**
